# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменные окружения
ENV POSTGRES_DB=EasyShopDocker
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=pa33word

# Открываем порт PostgreSQL
EXPOSE 5432
